[build]
# Install dependencies manually, then use make build
buildCommand = "npm install && go install github.com/a-h/templ/cmd/templ@latest && go install github.com/air-verse/air@latest && make build"

[deploy]
# Start the compiled Go binary
startCommand = "./mini-blog"

# Railway will check this path to ensure the service is healthy
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE" 