[build]
nixpacksPlan.providers = ["node", "go"]
buildCommand = "make install-tools && make build"

[deploy]
startCommand = "./mini-blog"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"