[build]
nixpacksPlan.providers = ["node", "go"]
buildCommand = "npm install && export PATH=$PATH:./node_modules/.bin && npm run build && go install github.com/a-h/templ/cmd/templ@latest && templ generate && go build -o mini-blog ."

[deploy]
startCommand = "./mini-blog"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"