[build]
nixpacksPlan.phases.build.paths = ["/app/node_modules/.bin"]
nixpacksPlan.phases.build.cmds = ["make install-tools", "make build"]
nixpacksPlan.providers = ["node", "go"]

[deploy]
startCommand = "./mini-blog"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"